version: "3.9"

services:
  angularprojectdev:
    image: lander22/angularprojectsimplilearn:dev
    build:
      context: ..
      dockerfile: deployment/DockerfileDev
    ports:
      - "4201:4200"
    volumes:
      - vol:/app/src
      #- /home/eellaandeergmai/angularProject/first-project/src:/app/src
    
  angularproject:
    image: lander22/angularprojectsimplilearn:pro
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "4202:4200"     
 
volumes:
  vol:
      